[package]
name = "relay"
version = "0.5.0-beta"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "relay"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

relay_integrity = { workspace = true }
